services:
  - type: web
    name: Full_stack_project
    env: ruby
    region: frankfurt # or oregon
    plan: starter
    numInstances: 1
    buildCommand: ./bin/render-build.sh
    startCommand: REDIS_URL="redis://${REDIS_HOST}" bundle exec puma -C config/puma.rb
    domains:
      - Mororcycle.com # replace with your domain name
    envVars:
      - key: DATABASE_URL
        fromDatabase: name: myapp-db property: connectionString
