services:      
    - type: web
    name: Full_stack_project
    env: ruby
    region: frankfurt
    plan: starter
    numInstances: 1
    buildCommand: ./bin/render-build.sh
    startCommand: bundle exec rails server -p $PORT
  - type: worker
    name: Full_stack_project
    env: ruby
    region: frankfurt
    plan: starter
    numInstances: 1
    buildCommand: ./bin/render-build.sh
    startCommand: bundle exec sidekiq
addons:
  - type: postgres
    version: "13"
    name: Full_stack_project
    env: ruby
    region: frankfurt
    plan: starter    
