services:
  - type: web
    name: Full_stack_project
    env: ruby
    region: frankfurt
    plan: starter
    numInstances: 1
    buildCommand: bundle install; bundle exec rake assets:precompile; bundle exec rake assets:clean;
    startCommand: bundle exec puma -t 5:5 -p ${PORT:-3000} -e ${RACK_ENV:-development}
    domains:
      - bike.com
    envVars:
      - key: RAILS_ENV
        value: production