services:
  - type: web
    name: Full_stack_project
    env: ruby
    region: frankfurt
    plan: starter
    numInstances: 1
    buildCommand: ./bin/render-build.sh
    startCommand: REDIS_URL="redis://${REDIS_HOST}" bundle exec puma -C config/puma.rb
    domains:
      - example.com
    envVars:
      - key: RAILS_ENV
        value: production