---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/motorcycles":
    get:
      summary: list motorcycles
      responses:
        '200':
          description: successful
    post:
      summary: create motorcycle
      responses:
        '200':
          description: successful
  "/api/v1/motorcycles/new":
    get:
      summary: new motorcycle
      responses:
        '200':
          description: successful
  "/api/v1/motorcycles/{id}/edit":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: edit motorcycle
      responses:
        '200':
          description: successful
  "/api/v1/motorcycles/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show motorcycle
      responses:
        '200':
          description: successful
    patch:
      summary: update motorcycle
      responses:
        '200':
          description: successful
    put:
      summary: update motorcycle
      responses:
        '200':
          description: successful
    delete:
      summary: delete motorcycle
      responses:
        '200':
          description: successful
  
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: http://localhost:3000